_question       = Pharm_Model_Question("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
_question.answers.append(Pharm_Model_Answer(False, "B. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
_question.answers.append(Pharm_Model_Answer(False, "C. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
_question.answers.append(Pharm_Model_Answer(False, "D. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
_question.answers.append(Pharm_Model_Answer(False, "E. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))


_question       = Pharm_Model_Question("1.1 Sistemul nervos din punct de vedere morfologic si functional, este constituit din:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Sistemul nervos somatic, ce regleaza activitatea organelor interne"))
_question.answers.append(Pharm_Model_Answer(False, "B. Neuroni şi celulele gliale"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Sistemul nervos somatic, al vietii de relatie"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sistemul nervos vegetativ, coordonator al activitatii viscerelor"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sistemul nervos vegetativ, ce cuprinde sistemul nervos central si sistemul nervos periferic"))

_question       = Pharm_Model_Question("1.2 Sistemul nervos vegetativ regleaza si coordoneaza activitatea organelor interne ce indeplinesc urmatoarele functii:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. De nutritie"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Respiratorie"))
_question.answers.append(Pharm_Model_Answer(False, "C. De aparare si adaptare a organismului si diversi stimuli din mediul extern"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Circulatorie"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Excretorie"))


_question       = Pharm_Model_Question("1.3 Care dintre următoarele enunţuri sunt corecte pentru a numera structuri componente ale sistemului nervos central?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,   "A. Emisferele cerebrale, diencefal, cerebel, trunchiul cerebral și măduvaspinării"))
_question.answers.append(Pharm_Model_Answer(False,  "B. Encefal, nervii cranieni şi nervii spinali"))
_question.answers.append(Pharm_Model_Answer(True,   "C. Encefal și măduva spinării"))
_question.answers.append(Pharm_Model_Answer(False,  "D. Măduva spinării, cerebel și trunchiul cerebral"))
_question.answers.append(Pharm_Model_Answer(False,  "E. Măduva spinării, diencefal și cerebel"))

_question       = Pharm_Model_Question("1.4 Din punct de vedere funcțional nervii sunt:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Motori"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Senzitivi"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Micşti"))
_question.answers.append(Pharm_Model_Answer(False, "D. Cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "E. Spinali"))


_question       = Pharm_Model_Question("1.5 Precizati afirmatiile corecte cu privire la neuronii receptori")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Pot fi neuroni somatosenzitivi"))
_question.answers.append(Pharm_Model_Answer(False, "B. Prin axionii lor sunt in legatura cu organele efectoare"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Sunt neuroni pseudounipolari"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Cu dendritele lor lungi receptioneaza stimuli din mediul exterior sau din interiorul organismului"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Pot fi neuroni viscerosenzitivi"))

_question       = Pharm_Model_Question("1.6 Selectaţi răspunsurile false cu privire la neuronii motori:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Sunt de dimensiuni mari, dar au un axon scurt"))
_question.answers.append(Pharm_Model_Answer(False, "B. Sunt neuroni multipolari"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Prin dendritele lor determină contracția musculaturii netede și scheletice a organismului"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Axonii lor recepționează stimulii din mediul exterior sau din interiorul organismului"))
_question.answers.append(Pharm_Model_Answer(False, "E. Pot fi visceromotori sau somatomotori"))

_question       = Pharm_Model_Question("1.7 Selectaţi răspunsurile corecte cu privire la neuronii intercalari:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Se mai numesc şi neuroni de asociaţie"))
_question.answers.append(Pharm_Model_Answer(False, "B. Au dimensiuni mari"))
_question.answers.append(Pharm_Model_Answer(False, "C. Prin axonii lor recepționează stimulii din mediul exterior al organismului"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Realizează legătura între neuronii senzitivi şi motori"))
_question.answers.append(Pharm_Model_Answer(False, "E. Facilitează legătura între neuronii de asociaţie şi neuronii multipolari"))

_question       = Pharm_Model_Question("1.8 Selectaţi răspunsurile corecte cu privire la conducerea saltatorie:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Este caracteristică fibrelor nervoase amielinice"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este rapidă"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Se întâlneşte în fibrele nervoase mielinice"))
_question.answers.append(Pharm_Model_Answer(False, "D. Se desfăşoară din aproape în aproape"))
_question.answers.append(Pharm_Model_Answer(False, "E. Are viteză mică de transmitere a influxului nervos"))

_question       = Pharm_Model_Question("1.9 Prin dendrite impulsul nervos este condus:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. La astrocite"))
_question.answers.append(Pharm_Model_Answer(False, "B. Centrifug"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Centripet"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Spre corpul neuronului"))
_question.answers.append(Pharm_Model_Answer(False, "E. Din aproape în aproape"))

_question       = Pharm_Model_Question("1.10 Selectaţi afirmaţiile corecte cu privire la teaca Schwann:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Este una din tecile ce învelesc fibra nervoasă"))
_question.answers.append(Pharm_Model_Answer(False, "B. Funcţionează ca izolator termic al fibrei nervoase"))
_question.answers.append(Pharm_Model_Answer(False, "C. Are rol trofic"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Este formată din celulele gliale Schwann"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Între două celule Schwann se găsesc strangulațiile Ranvier"))

_question       = Pharm_Model_Question("1.11 Precizati afirmatiile corecte cu privire la teaca Henle:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Faciliteaza conducerea saltatorie a impulsului nervos"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este dispusa la exteriorul fibrei nervoase"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Acopera firbra nervoasa in intregime"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Are o structura conjuctiva"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Are rol de protectie a fibrei nervoase"))

_question       = Pharm_Model_Question("1.12 Sinapsele reprezinta legaturile morfofunctionale:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Intre doi neuroni (neuroneuronale)"))
_question.answers.append(Pharm_Model_Answer(False, "B. De colaborare intre doua structuri efectoare diferite (muschi si glande)"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Stabilite intre neuroni si alte structuri efectoare (muschi sau glande)"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Cu rol in elaborarea unor raspunsuri reflexe sau voluntare"))
_question.answers.append(Pharm_Model_Answer(True,  "E. La baza reactiilor de aparare si adaptare a organismului la conditiile variabile ale mediului"))

_question       = Pharm_Model_Question("1.13 Care din afirmatiile urmatoare referitoare la actul reflex sunt adevarate?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Este proprietatea fundamentala a organismelor vii de-a reactiona la prezenta unui stimul printr-o depolarizare a membranei celulare"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Are drept suport anatomic arcul reflex"))
_question.answers.append(Pharm_Model_Answer(False, "C. Arcul reflex are semnificatie identica cu cea a actului reflex"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Reprezinta reactia de raspuns a organismului la actiunea unui excitant din mediul extern sau intern asupra unui receptor"))
_question.answers.append(Pharm_Model_Answer(False, "E. Este proprietata fundamentala a organismelor vii de-a propaga unda de depolarizare de-a lungul membranei celulare censecutiva aplicarii unui stimul cu intensitate prag"))

_question       = Pharm_Model_Question("1.14 Arcul reflex somatic este alcătuit din următoarele elemente anatomice:")
_category.questions.append(_question) 
_question.answers.append(Pharm_Model_Answer(True,  "A. Calea aferentă"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Receptorul"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Calea eferentă"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Centrul reflex"))
_question.answers.append(Pharm_Model_Answer(False, "E. Efectorul, mușchiul neted"))

_question       = Pharm_Model_Question("1.15. Precizaţi afirmaţiile corecte cu privire la reflexele miotatice:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Reprezintă un răspuns la acţiunea unui stimul nociv"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Sunt reflexe monosinapiice"))
_question.answers.append(Pharm_Model_Answer(False, "C. Se mai numesc şi reflexe nociceptiveitui"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Au arcul reflex constituit doar din doi neuroni"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Pot fi puse în evidenţă la nivelul tendonului lui Ahile"))

_question       = Pharm_Model_Question("1.16 Ramura meningeala a nervilor spinali:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Faciliteaza legatura acestora cu ganglionii paravertebrali"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Contine doar fibre vegetative"))
_question.answers.append(Pharm_Model_Answer(False, "C. Se distribuie la pielea spatelui"))
_question.answers.append(Pharm_Model_Answer(False, "D. Se distribuie la pielea capului"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Asigura inervatia meningelui spinal"))

_question       = Pharm_Model_Question("1.17. Ramura dorsală a nervului spinal conţine:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Exclusiv fibre motorii implicate în contracția musculaturii netede tegumentare"))
_question.answers.append(Pharm_Model_Answer(False, "B. Exclusiv fibre senzitive ce asigură inervaţia meningelui"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Atât fibre motorii, senzitive cât şi vegetative"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Fibre motorii cu rol în contracția musculaturii spatelui"))
_question.answers.append(Pharm_Model_Answer(False, "E. Fibre care se distribuie la muşchii intercostali"))

_question       = Pharm_Model_Question("1.18 Precizaţi afirmaţiile corecte cu privire la nervii spinali:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Sunt în număr de 31 perechi"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Prezintă cinci ramuri: dorsală, ventrală, meningeală, comunicanta albă și comunicanta cenuşie"))
_question.answers.append(Pharm_Model_Answer(False, "C. Sunt nervi senzitivi, motori şi micşti, precum nervii cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "D. Fără nicio excepție, toți participă la formarea de plexuri"))
_question.answers.append(Pharm_Model_Answer(False, "E. Prezintă cinci elemente componente: o rădăcină, un trunchi şi 3 ramuri periferice"))

_question       = Pharm_Model_Question("1.19 Care dintre următorii nervi cranieni sunt senzoriali?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. I"))
_question.answers.append(Pharm_Model_Answer(False, "B. VI"))
_question.answers.append(Pharm_Model_Answer(False, "C. IV"))
_question.answers.append(Pharm_Model_Answer(True,  "D. II"))
_question.answers.append(Pharm_Model_Answer(True,  "E. VIII"))

_question       = Pharm_Model_Question("1.20 Care dintre următorii nervi cranieni sunt motori?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. III"))
_question.answers.append(Pharm_Model_Answer(True,  "B. IV"))
_question.answers.append(Pharm_Model_Answer(False, "C. VIII"))
_question.answers.append(Pharm_Model_Answer(False, "D. VII"))
_question.answers.append(Pharm_Model_Answer(True,  "E. VI"))

_question       = Pharm_Model_Question("1.21 Care dintre următorii nervi cranieni sunt micști?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. IV"))
_question.answers.append(Pharm_Model_Answer(True,  "B. V"))
_question.answers.append(Pharm_Model_Answer(True,  "C. VII"))
_question.answers.append(Pharm_Model_Answer(True,  "D. X"))
_question.answers.append(Pharm_Model_Answer(False, "E. XII"))

_question       = Pharm_Model_Question("1.22 Precizaţi afirmaţiile corecte cu privire la nervii oculomotori:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reprezintă perechea III de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "B. Reprezintă perechea VI de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Sunt nervi motori care au și fibre vegetative motori"))
_question.answers.append(Pharm_Model_Answer(False, "D. Sunt nervi senzitivi care au si fibre parasimpatice"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Inerveaza muschii globului ocular (drept inferior, drept superior, drept intern şi oblic inferior) prin fibrele motorii somatice"))

_question       = Pharm_Model_Question("1.23 Selectati afirmatiile corecte cu privire la nervii trohleari")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Reprezinta perechea VII de nervi craniei"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezinta perechea IV de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "C. Inerveaza muschiul oblic inferior al globului ocular"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi motori"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Inerveaza muschiul oblic superior al globului ocular"))

_question       = Pharm_Model_Question("1.24 Selectati afirmatiile corecte referitoare la nervii trigemeni")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Inerveaza muschii masticatori prin fibrele senzoriale ale ramurii mandibulare"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezinta perechea V de nervi craniei"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Inerveaza muschii masticatori prin fibrele motorii ale ramurii lor mandibulare"))
_question.answers.append(Pharm_Model_Answer(False, "D. Sunt nervi motori care au si fibre parasimpatice"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Sunt nervi micsti"))

_question       = Pharm_Model_Question("1.25 Selectati afirmatiile corecte referitoare la nervii abducens")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Inerveaza muschiul drept extern al globului ocular"))
_question.answers.append(Pharm_Model_Answer(False, "B. Reprezinta perechea a IV de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Reprezinta perechea a VI de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi motori"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sunt nervi senzitivi care au si fibre vegetative"))

_question       = Pharm_Model_Question("1.26. Fibrele vegetative ale nervului facial inervează glandele:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Parotide"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Lacrimale"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Submandibulare"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sublinguale"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sudoripare"))

_question       = Pharm_Model_Question("1.27. Selectaţi afirmațiile corecte referitoare la nervii vestibulocohleari:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Sunt nervi senzitivi"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Culeg informaţii de la nivelul organului Corti din urechea interna, prin ramura acustica"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Recepţionează informaţii de la receptorii statici din urechea interna, prin ramura vestibulara"))
_question.answers.append(Pharm_Model_Answer(False, "D. Au pe traiectul lor ganglionul lui Scarpa si ganglionul spinal"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sunt nervi micşti"))

_question       = Pharm_Model_Question("1.28. Selectaţi afirmaţiile corecte referitoare la nervii vagi")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Inervează unii muşchi ai laringelui"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Inervează majoritatea viscerelor toracice si abdominale"))
_question.answers.append(Pharm_Model_Answer(False, "C. Reprezintă perechea a IV de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi cranieni micsti"))
_question.answers.append(Pharm_Model_Answer(False, "E. Inervează muşchiul oblic superior al globului ocular"))

_question       = Pharm_Model_Question("1.29. Selectaţi afirmaţiile corecte referitoare la nervii glosofaringieni:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Reprezintă perechea IV de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezintă perechea IX de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "C. Sunt nervi senzoriali"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi micşti"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Inervează glandele salivare parotide prin fibrele vegetative motorii"))

_question       = Pharm_Model_Question("1.30. Selectaţi afirmaţiile corecte referitoare la nervii accesori:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Reprezintă perechea VIII de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezintă perechea XI de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Inervează muşchii sternocleidomastoidian şi trapez"))
_question.answers.append(Pharm_Model_Answer(False, "D. Sunt nervi senzoriali"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Sunt nervi motori"))

_question       = Pharm_Model_Question("1.31. Precizaţi afirmaţiile corecte referitoare la nervii hipogloși:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Inervează muşchii limbii"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezintă perechea XII de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "C. Inervează unii muşchi ai laringelui"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi motori"))
_question.answers.append(Pharm_Model_Answer(False, "E. Inervează glandele sublinguale"))

_question       = Pharm_Model_Question("1.32. Selectaţi afirmaţiile corecte referitoare la nervii olfactivi:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reprezintă perechea I de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "B. Reprezintă perechea III de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Sunt nervi senzoriali"))
_question.answers.append(Pharm_Model_Answer(False, "D. Sunt nervi micşti"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Conduc informaţii legate de miros"))

_question       = Pharm_Model_Question("1.33. Selectaţi afirmaţiile corecte referitoare la nervii optici:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Reprezintă perechea IV de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezintă perechea II de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "C. Sunt nervi motori"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi senzoriali"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Conduc informaţii legate de vaz"))

_question       = Pharm_Model_Question("1.34. Reflexele vegetative care se închid în trunchiul cerebral sunt reprezentate de:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reflexele respiratorii și cardiovasculare — în bulb"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reflexele de salivaţie pentru glandele parotide — în bulb"))
_question.answers.append(Pharm_Model_Answer(False, "C. Reflexele de micţiune, defecaţie şi sexuale"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Reflexele lacrimale şi de salivaţie pentru glandelesublinguale si  submandibulare — în punte"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Reflexele pupilare fotomotorii — în mezencefal"))

_question       = Pharm_Model_Question("1.35 Reflexele vegetative care se inchid in maduva spinarii sunt reprezentate de:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reflexele de mictiune, defecatie si sexuale"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reflexul pupilodidatator"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Reflexele de sudoraţie"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Reflexul cardioaccelerator"))
_question.answers.append(Pharm_Model_Answer(False, "E. Reflexele pupilare fotomotorii"))

_question       = Pharm_Model_Question("1.36 Hipotalamusul, centru al integrarii vegetative, indeplineste in organism urmatoarele activitati:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Mentinerea constantă a temperaturii corpului prin păstrarea unuicehuioru intre procesele de termogeneză şi termoliză"))
_question.answers.append(Pharm_Model_Answer(False, "B. Reglarea proceselor de micţiune şi defecaţie"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Reglarea metabolismului intermediar"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Reglarea funcţiilor sexuale"))
_question.answers.append(Pharm_Model_Answer(False, "E. Integrarea impulsurilor nervoase ascendente"))

_question       = Pharm_Model_Question("1.37. Parasimpaticul cranian îşi are originile în nucleii:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Dorsal al vagului"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Accesor al oculomotorului"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Salivator inferior"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Salivator superior"))
_question.answers.append(Pharm_Model_Answer(False, "E. Ambiguu din bulb"))

_question       = Pharm_Model_Question("1.38. Stimularea simpatică produce la nivelul cordului:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Creşterea frecvenței cardiace"))
_question.answers.append(Pharm_Model_Answer(False, "B. Scăderea frecvenţei cardiace"))
_question.answers.append(Pharm_Model_Answer(False, "C. Bradicardie"))
_question.answers.append(Pharm_Model_Answer(False, "D. Scăderea forței de contracție a miocardului"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Creşterea forței de contracție a miocardului"))

_question       = Pharm_Model_Question("1.39. Stimularea simpatică produce la nivelul tractului gastrointestinal:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Relaxarea sfincterelor, cu deschiderea lor"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Constricţia sfincterelor digestive"))
_question.answers.append(Pharm_Model_Answer(False, "C. Creşterea peristaltismului"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Diminuarea tonusului si a motilităţii"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Inhibarea secreției gastrice si intestinale"))

_question       = Pharm_Model_Question("1.40 Stimularea simpatica produce la nivelul bronhiilor")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Relaxarea sfincterelor, cu deschiderea lor"))
_question.answers.append(Pharm_Model_Answer(False, "B. Constrictia sfincterelor digestive"))
_question.answers.append(Pharm_Model_Answer(False, "C. Cresterea peristaltismului"))
_question.answers.append(Pharm_Model_Answer(False, "D. Diminuarea tonusului si a mortalitatii"))
_question.answers.append(Pharm_Model_Answer(False, "E. Inhibarea scretiei gastrice si intestinale"))

_question       = Pharm_Model_Question("1.41. Stimularea sistemului simpatic produce la nivelul tractului urinar:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Contracţia sfincterului vezical extern"))
_question.answers.append(Pharm_Model_Answer(False, "B. Contracţia sfincterului vezical intern"))
_question.answers.append(Pharm_Model_Answer(False, "C. Relaxarea muşchiului vezical"))
_question.answers.append(Pharm_Model_Answer(False, "D. Creşterea debitului urinar"))
_question.answers.append(Pharm_Model_Answer(False, "E. Creşterea secreției de renină"))