_question       = Pharm_Model_Question("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
_question.answers.append(Pharm_Model_Answer(False, "B. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
_question.answers.append(Pharm_Model_Answer(False, "C. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
_question.answers.append(Pharm_Model_Answer(False, "D. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
_question.answers.append(Pharm_Model_Answer(False, "E. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))


_question       = Pharm_Model_Question("1.1 Sistemul nervos din punct de vedere morfologic si functional, este constituit din:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Sistemul nervos somatic, ce regleaza activitatea organelor interne"))
_question.answers.append(Pharm_Model_Answer(False, "B. Neuroni şi celulele gliale"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Sistemul nervos somatic, al vietii de relatie"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sistemul nervos vegetativ, coordonator al activitatii viscerelor"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sistemul nervos vegetativ, ce cuprinde sistemul nervos central si sistemul nervos periferic"))

_question       = Pharm_Model_Question("1.2 Sistemul nervos vegetativ regleaza si coordoneaza activitatea organelor interne ce indeplinesc urmatoarele functii:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. De nutritie"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Respiratorie"))
_question.answers.append(Pharm_Model_Answer(False, "C. De aparare si adaptare a organismului si diversi stimuli din mediul extern"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Circulatorie"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Excretorie"))


_question       = Pharm_Model_Question("1.3 Care dintre următoarele enunţuri sunt corecte pentru a numera structuri componente ale sistemului nervos central?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,   "A. Emisferele cerebrale, diencefal, cerebel, trunchiul cerebral și măduvaspinării"))
_question.answers.append(Pharm_Model_Answer(False,  "B. Encefal, nervii cranieni şi nervii spinali"))
_question.answers.append(Pharm_Model_Answer(True,   "C. Encefal și măduva spinării"))
_question.answers.append(Pharm_Model_Answer(False,  "D. Măduva spinării, cerebel și trunchiul cerebral"))
_question.answers.append(Pharm_Model_Answer(False,  "E. Măduva spinării, diencefal și cerebel"))

_question       = Pharm_Model_Question("1.4 Din punct de vedere funcțional nervii sunt:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Motori"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Senzitivi"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Micşti"))
_question.answers.append(Pharm_Model_Answer(False, "D. Cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "E. Spinali"))


_question       = Pharm_Model_Question("1.5 Precizati afirmatiile corecte cu privire la neuronii receptori")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Pot fi neuroni somatosenzitivi"))
_question.answers.append(Pharm_Model_Answer(False, "B. Prin axionii lor sunt in legatura cu organele efectoare"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Sunt neuroni pseudounipolari"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Cu dendritele lor lungi receptioneaza stimuli din mediul exterior sau din interiorul organismului"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Pot fi neuroni viscerosenzitivi"))

_question       = Pharm_Model_Question("1.6 Selectaţi răspunsurile false cu privire la neuronii motori:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Sunt de dimensiuni mari, dar au un axon scurt"))
_question.answers.append(Pharm_Model_Answer(False, "B. Sunt neuroni multipolari"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Prin dendritele lor determină contracția musculaturii netede și scheletice a organismului"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Axonii lor recepționează stimulii din mediul exterior sau din interiorul organismului"))
_question.answers.append(Pharm_Model_Answer(False, "E. Pot fi visceromotori sau somatomotori"))

_question       = Pharm_Model_Question("1.7 Selectaţi răspunsurile corecte cu privire la neuronii intercalari:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Se mai numesc şi neuroni de asociaţie"))
_question.answers.append(Pharm_Model_Answer(False, "B. Au dimensiuni mari"))
_question.answers.append(Pharm_Model_Answer(False, "C. Prin axonii lor recepționează stimulii din mediul exterior al organismului"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Realizează legătura între neuronii senzitivi şi motori"))
_question.answers.append(Pharm_Model_Answer(False, "E. Facilitează legătura între neuronii de asociaţie şi neuronii multipolari"))

_question       = Pharm_Model_Question("1.8 Selectaţi răspunsurile corecte cu privire la conducerea saltatorie:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Este caracteristică fibrelor nervoase amielinice"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este rapidă"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Se întâlneşte în fibrele nervoase mielinice"))
_question.answers.append(Pharm_Model_Answer(False, "D. Se desfăşoară din aproape în aproape"))
_question.answers.append(Pharm_Model_Answer(False, "E. Are viteză mică de transmitere a influxului nervos"))

_question       = Pharm_Model_Question("1.9 Prin dendrite impulsul nervos este condus:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. La astrocite"))
_question.answers.append(Pharm_Model_Answer(False, "B. Centrifug"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Centripet"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Spre corpul neuronului"))
_question.answers.append(Pharm_Model_Answer(False, "E. Din aproape în aproape"))

_question       = Pharm_Model_Question("1.10 Selectaţi afirmaţiile corecte cu privire la teaca Schwann:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Este una din tecile ce învelesc fibra nervoasă"))
_question.answers.append(Pharm_Model_Answer(False, "B. Funcţionează ca izolator termic al fibrei nervoase"))
_question.answers.append(Pharm_Model_Answer(False, "C. Are rol trofic"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Este formată din celulele gliale Schwann"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Între două celule Schwann se găsesc strangulațiile Ranvier"))

_question       = Pharm_Model_Question("1.11 Precizati afirmatiile corecte cu privire la teaca Henle:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Faciliteaza conducerea saltatorie a impulsului nervos"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este dispusa la exteriorul fibrei nervoase"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Acopera firbra nervoasa in intregime"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Are o structura conjuctiva"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Are rol de protectie a fibrei nervoase"))

_question       = Pharm_Model_Question("1.12 Sinapsele reprezinta legaturile morfofunctionale:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Intre doi neuroni (neuroneuronale)"))
_question.answers.append(Pharm_Model_Answer(False, "B. De colaborare intre doua structuri efectoare diferite (muschi si glande)"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Stabilite intre neuroni si alte structuri efectoare (muschi sau glande)"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Cu rol in elaborarea unor raspunsuri reflexe sau voluntare"))
_question.answers.append(Pharm_Model_Answer(True,  "E. La baza reactiilor de aparare si adaptare a organismului la conditiile variabile ale mediului"))

_question       = Pharm_Model_Question("1.13 Care din afirmatiile urmatoare referitoare la actul reflex sunt adevarate?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Este proprietatea fundamentala a organismelor vii de-a reactiona la prezenta unui stimul printr-o depolarizare a membranei celulare"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Are drept suport anatomic arcul reflex"))
_question.answers.append(Pharm_Model_Answer(False, "C. Arcul reflex are semnificatie identica cu cea a actului reflex"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Reprezinta reactia de raspuns a organismului la actiunea unui excitant din mediul extern sau intern asupra unui receptor"))
_question.answers.append(Pharm_Model_Answer(False, "E. Este proprietata fundamentala a organismelor vii de-a propaga unda de depolarizare de-a lungul membranei celulare censecutiva aplicarii unui stimul cu intensitate prag"))

_question       = Pharm_Model_Question("1.14 Arcul reflex somatic este alcătuit din următoarele elemente anatomice:")
_category.questions.append(_question) 
_question.answers.append(Pharm_Model_Answer(True,  "A. Calea aferentă"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Receptorul"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Calea eferentă"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Centrul reflex"))
_question.answers.append(Pharm_Model_Answer(False, "E. Efectorul, mușchiul neted"))

_question       = Pharm_Model_Question("1.15. Precizaţi afirmaţiile corecte cu privire la reflexele miotatice:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Reprezintă un răspuns la acţiunea unui stimul nociv"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Sunt reflexe monosinapiice"))
_question.answers.append(Pharm_Model_Answer(False, "C. Se mai numesc şi reflexe nociceptiveitui"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Au arcul reflex constituit doar din doi neuroni"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Pot fi puse în evidenţă la nivelul tendonului lui Ahile"))

_question       = Pharm_Model_Question("1.16 Ramura meningeala a nervilor spinali:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Faciliteaza legatura acestora cu ganglionii paravertebrali"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Contine doar fibre vegetative"))
_question.answers.append(Pharm_Model_Answer(False, "C. Se distribuie la pielea spatelui"))
_question.answers.append(Pharm_Model_Answer(False, "D. Se distribuie la pielea capului"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Asigura inervatia meningelui spinal"))

_question       = Pharm_Model_Question("1.17. Ramura dorsală a nervului spinal conţine:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Exclusiv fibre motorii implicate în contracția musculaturii netede tegumentare"))
_question.answers.append(Pharm_Model_Answer(False, "B. Exclusiv fibre senzitive ce asigură inervaţia meningelui"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Atât fibre motorii, senzitive cât şi vegetative"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Fibre motorii cu rol în contracția musculaturii spatelui"))
_question.answers.append(Pharm_Model_Answer(False, "E. Fibre care se distribuie la muşchii intercostali"))

_question       = Pharm_Model_Question("1.18 Precizaţi afirmaţiile corecte cu privire la nervii spinali:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Sunt în număr de 31 perechi"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Prezintă cinci ramuri: dorsală, ventrală, meningeală, comunicanta albă și comunicanta cenuşie"))
_question.answers.append(Pharm_Model_Answer(False, "C. Sunt nervi senzitivi, motori şi micşti, precum nervii cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "D. Fără nicio excepție, toți participă la formarea de plexuri"))
_question.answers.append(Pharm_Model_Answer(False, "E. Prezintă cinci elemente componente: o rădăcină, un trunchi şi 3 ramuri periferice"))

_question       = Pharm_Model_Question("1.19 Care dintre următorii nervi cranieni sunt senzoriali?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. I"))
_question.answers.append(Pharm_Model_Answer(False, "B. VI"))
_question.answers.append(Pharm_Model_Answer(False, "C. IV"))
_question.answers.append(Pharm_Model_Answer(True,  "D. II"))
_question.answers.append(Pharm_Model_Answer(True,  "E. VIII"))

_question       = Pharm_Model_Question("1.20 Care dintre următorii nervi cranieni sunt motori?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. III"))
_question.answers.append(Pharm_Model_Answer(True,  "B. IV"))
_question.answers.append(Pharm_Model_Answer(False, "C. VIII"))
_question.answers.append(Pharm_Model_Answer(False, "D. VII"))
_question.answers.append(Pharm_Model_Answer(True,  "E. VI"))

_question       = Pharm_Model_Question("1.21 Care dintre următorii nervi cranieni sunt micști?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. IV"))
_question.answers.append(Pharm_Model_Answer(True,  "B. V"))
_question.answers.append(Pharm_Model_Answer(True,  "C. VII"))
_question.answers.append(Pharm_Model_Answer(True,  "D. X"))
_question.answers.append(Pharm_Model_Answer(False, "E. XII"))

_question       = Pharm_Model_Question("1.22 Precizaţi afirmaţiile corecte cu privire la nervii oculomotori:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reprezintă perechea III de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "B. Reprezintă perechea VI de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Sunt nervi motori care au și fibre vegetative motori"))
_question.answers.append(Pharm_Model_Answer(False, "D. Sunt nervi senzitivi care au si fibre parasimpatice"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Inerveaza muschii globului ocular (drept inferior, drept superior, drept intern şi oblic inferior) prin fibrele motorii somatice"))

_question       = Pharm_Model_Question("1.23 Selectati afirmatiile corecte cu privire la nervii trohleari")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Reprezinta perechea VII de nervi craniei"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezinta perechea IV de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "C. Inerveaza muschiul oblic inferior al globului ocular"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi motori"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Inerveaza muschiul oblic superior al globului ocular"))

_question       = Pharm_Model_Question("1.24 Selectati afirmatiile corecte referitoare la nervii trigemeni")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Inerveaza muschii masticatori prin fibrele senzoriale ale ramurii mandibulare"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezinta perechea V de nervi craniei"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Inerveaza muschii masticatori prin fibrele motorii ale ramurii lor mandibulare"))
_question.answers.append(Pharm_Model_Answer(False, "D. Sunt nervi motori care au si fibre parasimpatice"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Sunt nervi micsti"))

_question       = Pharm_Model_Question("1.25 Selectati afirmatiile corecte referitoare la nervii abducens")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Inerveaza muschiul drept extern al globului ocular"))
_question.answers.append(Pharm_Model_Answer(False, "B. Reprezinta perechea a IV de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Reprezinta perechea a VI de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi motori"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sunt nervi senzitivi care au si fibre vegetative"))

_question       = Pharm_Model_Question("1.26. Fibrele vegetative ale nervului facial inervează glandele:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Parotide"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Lacrimale"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Submandibulare"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sublinguale"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sudoripare"))

_question       = Pharm_Model_Question("1.27. Selectaţi afirmațiile corecte referitoare la nervii vestibulocohleari:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Sunt nervi senzitivi"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Culeg informaţii de la nivelul organului Corti din urechea interna, prin ramura acustica"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Recepţionează informaţii de la receptorii statici din urechea interna, prin ramura vestibulara"))
_question.answers.append(Pharm_Model_Answer(False, "D. Au pe traiectul lor ganglionul lui Scarpa si ganglionul spinal"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sunt nervi micşti"))

_question       = Pharm_Model_Question("1.28. Selectaţi afirmaţiile corecte referitoare la nervii vagi")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Inervează unii muşchi ai laringelui"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Inervează majoritatea viscerelor toracice si abdominale"))
_question.answers.append(Pharm_Model_Answer(False, "C. Reprezintă perechea a IV de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi cranieni micsti"))
_question.answers.append(Pharm_Model_Answer(False, "E. Inervează muşchiul oblic superior al globului ocular"))

_question       = Pharm_Model_Question("1.29. Selectaţi afirmaţiile corecte referitoare la nervii glosofaringieni:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Reprezintă perechea IV de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezintă perechea IX de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "C. Sunt nervi senzoriali"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi micşti"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Inervează glandele salivare parotide prin fibrele vegetative motorii"))

_question       = Pharm_Model_Question("1.30. Selectaţi afirmaţiile corecte referitoare la nervii accesori:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Reprezintă perechea VIII de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezintă perechea XI de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Inervează muşchii sternocleidomastoidian şi trapez"))
_question.answers.append(Pharm_Model_Answer(False, "D. Sunt nervi senzoriali"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Sunt nervi motori"))

_question       = Pharm_Model_Question("1.31. Precizaţi afirmaţiile corecte referitoare la nervii hipogloși:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Inervează muşchii limbii"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezintă perechea XII de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "C. Inervează unii muşchi ai laringelui"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi motori"))
_question.answers.append(Pharm_Model_Answer(False, "E. Inervează glandele sublinguale"))

_question       = Pharm_Model_Question("1.32. Selectaţi afirmaţiile corecte referitoare la nervii olfactivi:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reprezintă perechea I de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "B. Reprezintă perechea III de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Sunt nervi senzoriali"))
_question.answers.append(Pharm_Model_Answer(False, "D. Sunt nervi micşti"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Conduc informaţii legate de miros"))

_question       = Pharm_Model_Question("1.33. Selectaţi afirmaţiile corecte referitoare la nervii optici:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Reprezintă perechea IV de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reprezintă perechea II de nervi cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "C. Sunt nervi motori"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt nervi senzoriali"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Conduc informaţii legate de vaz"))

_question       = Pharm_Model_Question("1.34. Reflexele vegetative care se închid în trunchiul cerebral sunt reprezentate de:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reflexele respiratorii și cardiovasculare — în bulb"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reflexele de salivaţie pentru glandele parotide — în bulb"))
_question.answers.append(Pharm_Model_Answer(False, "C. Reflexele de micţiune, defecaţie şi sexuale"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Reflexele lacrimale şi de salivaţie pentru glandelesublinguale si  submandibulare — în punte"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Reflexele pupilare fotomotorii — în mezencefal"))

_question       = Pharm_Model_Question("1.35 Reflexele vegetative care se inchid in maduva spinarii sunt reprezentate de:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reflexele de mictiune, defecatie si sexuale"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Reflexul pupilodidatator"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Reflexele de sudoraţie"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Reflexul cardioaccelerator"))
_question.answers.append(Pharm_Model_Answer(False, "E. Reflexele pupilare fotomotorii"))

_question       = Pharm_Model_Question("1.36 Hipotalamusul, centru al integrarii vegetative, indeplineste in organism urmatoarele activitati:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Mentinerea constantă a temperaturii corpului prin păstrarea unuicehuioru intre procesele de termogeneză şi termoliză"))
_question.answers.append(Pharm_Model_Answer(False, "B. Reglarea proceselor de micţiune şi defecaţie"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Reglarea metabolismului intermediar"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Reglarea funcţiilor sexuale"))
_question.answers.append(Pharm_Model_Answer(False, "E. Integrarea impulsurilor nervoase ascendente"))

_question       = Pharm_Model_Question("1.37. Parasimpaticul cranian îşi are originile în nucleii:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Dorsal al vagului"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Accesor al oculomotorului"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Salivator inferior"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Salivator superior"))
_question.answers.append(Pharm_Model_Answer(False, "E. Ambiguu din bulb"))

_question       = Pharm_Model_Question("1.38. Stimularea simpatică produce la nivelul cordului:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Creşterea frecvenței cardiace"))
_question.answers.append(Pharm_Model_Answer(False, "B. Scăderea frecvenţei cardiace"))
_question.answers.append(Pharm_Model_Answer(False, "C. Bradicardie"))
_question.answers.append(Pharm_Model_Answer(False, "D. Scăderea forței de contracție a miocardului"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Creşterea forței de contracție a miocardului"))

_question       = Pharm_Model_Question("1.39. Stimularea simpatică produce la nivelul tractului gastrointestinal:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Relaxarea sfincterelor, cu deschiderea lor"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Constricţia sfincterelor digestive"))
_question.answers.append(Pharm_Model_Answer(False, "C. Creşterea peristaltismului"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Diminuarea tonusului si a motilităţii"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Inhibarea secreției gastrice si intestinale"))

_question       = Pharm_Model_Question("1.40 Stimularea simpatica produce la nivelul bronhiilor")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Relaxarea sfincterelor, cu deschiderea lor"))
_question.answers.append(Pharm_Model_Answer(False, "B. Constrictia sfincterelor digestive"))
_question.answers.append(Pharm_Model_Answer(False, "C. Cresterea peristaltismului"))
_question.answers.append(Pharm_Model_Answer(False, "D. Diminuarea tonusului si a mortalitatii"))
_question.answers.append(Pharm_Model_Answer(False, "E. Inhibarea scretiei gastrice si intestinale"))

_question       = Pharm_Model_Question("1.41. Stimularea sistemului simpatic produce la nivelul tractului urinar:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Contracţia sfincterului vezical extern"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Contracţia sfincterului vezical intern"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Relaxarea muşchiului vezical"))
_question.answers.append(Pharm_Model_Answer(False, "D. Creşterea debitului urinar"))
_question.answers.append(Pharm_Model_Answer(False, "E. Creşterea secreției de renină"))

_question       = Pharm_Model_Question("1.42. Stimularea parasimpatică produce asupra irisului (mușchiul constrictor pupilar):")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Dilatarea pupilei"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Mioză"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Contracţie, cu micşorarea pupilei"))
_question.answers.append(Pharm_Model_Answer(False, "D. Relaxare (pentru vederea de aproape)"))
_question.answers.append(Pharm_Model_Answer(False, "E. Midriază"))

_question       = Pharm_Model_Question("1.43. Stimularea parasimpaticului produce la nivelul glandelor exocrine:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Creşterea secreției lacrimale"))
_question.answers.append(Pharm_Model_Answer(False, "B. Scăderea secreției lacrimale"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Secreţie salivară apoasă şi abundentă"))
_question.answers.append(Pharm_Model_Answer(False, "D. Diminuarea secreției glandelor salivare"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Creşterea secreţiilor digestive (gastrice şi intestinale)"))

_question       = Pharm_Model_Question("1.44. Stimularea  parasimpatică produce la nivelul tractului gastrointestinal:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Relaxarea sfincterelor digestive"))
_question.answers.append(Pharm_Model_Answer(False, "B. Constricţia sfincterelor"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Creşterea tonusului şi a motilității"))
_question.answers.append(Pharm_Model_Answer(False, "D. Scăderea tonusului şi a motilității"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Creşterea secreției gastrice şi intestinale"))

_question       = Pharm_Model_Question("1.45. Stimularea parasimpatică produce următoarele efecte în organism:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Coronarodilatație"))
_question.answers.append(Pharm_Model_Answer(False, "B. Bronhodilataţie"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Bronhoconstricție"))
_question.answers.append(Pharm_Model_Answer(False, "D. Midnază"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Mioză"))

_question       = Pharm_Model_Question("1.46. Selectaţi enunțurile corecte în legătură cu reflexele somatice ce se închid în trunchiul cerebral:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. De tuse, vomă şi deglutiţie: în bulb |"))
_question.answers.append(Pharm_Model_Answer(False, "B. De creștere a tonusului muscular: în nucleul roşu din mezencefal"))
_question.answers.append(Pharm_Model_Answer(True,  "C. De supt şi masticație: în punte"))
_question.answers.append(Pharm_Model_Answer(False, "D. De micțiune şi defecaţie"))
_question.answers.append(Pharm_Model_Answer(True,  "E. De diminuare a tonusului muscular: în nucleul roşu din mezencefal"))

_question       = Pharm_Model_Question("1.47 Care dintre urmatoarele enunturi sunt corecte in legatura cu lobii cerebelului")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Paleocerebelul este format din nucleii cerebelosi"))
_question.answers.append(Pharm_Model_Answer(False, "B. Paleocerebelul este format din nucleul dintat"))
_question.answers.append(Pharm_Model_Answer(False, "C. Neocerebelul este constitui din nucleii bazali"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Neocerebelul este constitui din emisferele cerebeloase si nucleul dintat"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Arhicerebelul se mai numeste si lobul floculonodular"))

_question       = Pharm_Model_Question("1.48 Reflexul necondiţionat este:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Innăscut"))
_question.answers.append(Pharm_Model_Answer(False, "B. Dobândit"))
_question.answers.append(Pharm_Model_Answer(False, "C. Un răspuns învăţat"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Comun tuturor indivizilor"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Constant şi invariabi]"))

_question       = Pharm_Model_Question("1.49 Selectaţi afirmaţiile corecte legate de calea sensibilităţii tactile fine:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Se mai numeşte şi epicritică"))
_question.answers.append(Pharm_Model_Answer(False, "B. Este numită şi protopatică"))
_question.answers.append(Pharm_Model_Answer(False, "C. Utilizează calea cordoanelor posterioare împreună cu sensibilitatea tactilă grosiera"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Este condusă pe calea fasciculelor spinobulbare Goll şi Burdach"))
_question.answers.append(Pharm_Model_Answer(False, "E. Urcă prin fasciculul spinotalamic lateral"))

_question       = Pharm_Model_Question("1.50 Selectaţi afirmaţiile corecte referitoare la calea sensibilităţii interoceptive:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reuneşte căi nespecifice în componența sa"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este condusă prin fasciculele spinotalamice"))
_question.answers.append(Pharm_Model_Answer(False, "C. Face parte din căile descendente ale măduvei"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Este condusă şi prin substanţa reticulată medulară"))
_question.answers.append(Pharm_Model_Answer(False, "E. Are o zonă de proiecţie corticală bine delimitată"))

_question       = Pharm_Model_Question("1.51 Selectaţi afirmaţiile corecte legate de calea sistemului piramidal:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Îşi are originea în cortexul cerebral"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Controlează motilitatea voluntară"))
_question.answers.append(Pharm_Model_Answer(False, "C. Face parte din căile ascendente"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Face parte din căile descendente"))
_question.answers.append(Pharm_Model_Answer(False, "E. Îşi are originea în cortexul cerebelos"))

_question       = Pharm_Model_Question("1.52 Fasciculele extrapiramidale sunt reprezentate de:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Fasciculul piramidal direct"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Fasciculul rubrospinal"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Fasciculul tectospinal"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Fasciculul olivospinal"))
_question.answers.append(Pharm_Model_Answer(False, "E. Fasciculul spinoreticulat"))

_question       = Pharm_Model_Question("1.53 Metatalamusul este un releu al sensibilităților:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Taculă, termică şi dureroasă"))
_question.answers.append(Pharm_Model_Answer(False, "B. Olfactivă"))
_question.answers.append(Pharm_Model_Answer(False, "C. Gustativă"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Auditivă"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Vizuală"))

_question       = Pharm_Model_Question("1.54. Talamusul este releu pentru toate sensibilitățile, cu excepția celor:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Olfactive"))
_question.answers.append(Pharm_Model_Answer(False, "B. Gustative"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Vizuale"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Auditive"))
_question.answers.append(Pharm_Model_Answer(False, "E. Termice si dureroase"))

_question       = Pharm_Model_Question("1.55 Substanta alba a emisferelor cerebrale este formata din fibre")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Postganglionare amielinice scurte"))
_question.answers.append(Pharm_Model_Answer(False, "B. Preganglionare mielinice lungi"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Comisurale"))
_question.answers.append(Pharm_Model_Answer(True,  "D. De asociaţie"))
_question.answers.append(Pharm_Model_Answer(True,  "E. De proiecţie"))

_question       = Pharm_Model_Question("1.56. Selectaţi afirmaţiile corecte legate de meningită:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Rezultă de obicei prin ruperea unui vas ateromatos"))
_question.answers.append(Pharm_Model_Answer(False, "B. Este o boală inflamatorie acută a encefalului"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Se caracterizează printr-o inflamație a meningelui de la nivel spinal sau cerebral"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Poate avea multiple etiologii: bacteriene, virale, toxice"))
_question.answers.append(Pharm_Model_Answer(False, "E. Este consecutivă unei hemoragii cerebrale posttraumatice"))

_question       = Pharm_Model_Question("1.57. Selectaţi afirmaţiile corecte legate de encefalită:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Boala poate fi de cauză inflamatorie acută a țesutului cerebral"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Boala poate fi de cauză infecțioasă, virală sau bacteriană"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Se manifestă prin disfuncţii motorii cerebrale (paralizii, pareze)"))
_question.answers.append(Pharm_Model_Answer(False, "D. Este caracterizată prin crize epileptice izolate"))
_question.answers.append(Pharm_Model_Answer(False, "E. Este declanșată de ruperea unui anevrism cerebral"))

_question       = Pharm_Model_Question("1.58. Selectaţi afirmaţiile corecte legate de hemoragiile cerebrale:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Pot evolua spre comă"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Rezultă de obicei prin ruperea unui vas cerebral la o persoană ce suferă de hipertensiune arterială"))
_question.answers.append(Pharm_Model_Answer(False, "C. Sunt complicaţii posibile ale encefalitelor"))
_question.answers.append(Pharm_Model_Answer(False, "D. Apar frecvent în cursul stărilor febrile la sugar şi copilul mic"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Pot să se constituie şi ca urmare a unor traumatisme cerebrale"))

_question       = Pharm_Model_Question("1.59 Cauzele cele mai frecvente ale comei sunt reprezentate de:")
_category.questions.append(_question) 
_question.answers.append(Pharm_Model_Answer(True,  "A. Traumatismele cranio-cerebrale"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Hemoragiile cerebrale"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Intoxicaţiile"))
_question.answers.append(Pharm_Model_Answer(False, "D. Crizele de isterie"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Unele boli grave ale sistemului nervos central aflate in stadiul final"))

_question       = Pharm_Model_Question("1.60 Cauzele cele mai frecvente ale convulsiilor sunt reprezentate de:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Traumatismele cerebrale"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Hemoragiile cerebrale"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Epilepsie"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Stările febrile ia sugar şi copilul mic"))
_question.answers.append(Pharm_Model_Answer(False, "E. Reacţiile de hipersensibilitate inițiate de o bacterie sau un antigen"))

_question       = Pharm_Model_Question("1.61 Din punct de vedere al localizării nervii sunt:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Motori"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Cranieni"))
_question.answers.append(Pharm_Model_Answer(False, "C. Micşti"))
_question.answers.append(Pharm_Model_Answer(False, "D. Senzitivi"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Spinali"))

_question       = Pharm_Model_Question("1.62 Selectaţi afirmaţiile corecte cu privire la neuroni:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Sunt unitatea structurală și funcțională a sistemului şi țesutului nervos"))
_question.answers.append(Pharm_Model_Answer(False, "B. Îndeplinesc toţi aceeaşi funcţie în organism"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Prezintă proprietatea de excitabilitate"))
_question.answers.append(Pharm_Model_Answer(False, "D. Nu prezintă diferențe morfologice între ei"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Asigură conductibilitatea undei de depolarizare ca răspuns la excitația produsa de anumiti stimuli asupra lor"))

_question       = Pharm_Model_Question("1.63 Precizaţi rolurile pe care le îndeplineşte teaca de mielină la nivelul neuronului?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Izolator termic"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Trofic"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Protecţie"))
_question.answers.append(Pharm_Model_Answer(False, "D. De încetinire a conducerii impulsului nervos"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Izolator electric"))

_question       = Pharm_Model_Question("1.64 Selectati afirmatiile corecte cu privire la excitabilitate:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Este o caracteristică a tuturor celulelor din organismul uman"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este proprietatea fundamentală a unor celule vii (celule nervoase, musculare, etc.)"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Exprimă capacitatea celulei de a reacționa specific la acțiunea unor stimuli"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Se manifestă prin depolar de depolarizare de-a lungul membranei celulare"))
_question.answers.append(Pharm_Model_Answer(False, "E. Asigură propagarea undei de depolarizare de-a lungul membranei celulare"))

_question       = Pharm_Model_Question("1.65 Care dintre următoarele afirmatii referitoare la depolarizarea membranara sunt adevrate?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reprezinta modificarea polaritatii electrice a membranei celulare"))
_question.answers.append(Pharm_Model_Answer(False, "B. Se datoreaza modificarii repartitei sarcinilor electrice intre cele doua fete ale membranei, consecutiv intrarii ionului de potasiu in celula"))
_question.answers.append(Pharm_Model_Answer(False, "C. Poate fi generata si ca un raspuns al celulei la excitanti a caror intensitate este sub valoarea prag"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Este consecinta cresterii permeabilitatii membranaare pentru ionii de sodiu"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Este forma de manifestare a excitabilitatii unei celule"))

_question       = Pharm_Model_Question("1.66 Selectaţi afirmaţiile corecte cu privire la conducerea saltatorie")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Asigură conducerea din aproape în aproape a undei de depolarizare"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este caracteristică axonilor mielinizaţi"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Se datorează prezenţei strangulaţiilor Ranvier"))
_question.answers.append(Pharm_Model_Answer(False, "D. Imprimă o viteză mică de propagare potenţialului de acțiune"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Permite o viteză de conducere a undei de depolarizare în fibrele mielinice mult mai mare față de cea din fibrele amielinice"))

_question       = Pharm_Model_Question("1.67 Selectaţi ordinea corectă a etapelor implicate în transmiterea sinaptică")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Sinteza mediatorului — eliberarea în fanta sinaptică — acţiunea sa asupra membranei postsinaptice — apariţia potențialului postsinaptic excitator — inactivarea enzimatica a mediatorului"))
_question.answers.append(Pharm_Model_Answer(False, "B. Stocarea mediatorului în vezicule — eliberarea sa în fanta sinaptică — acțiunea sa asupra membranei postsinaptice — apariția potenţialului postsinaptic excitator"))
_question.answers.append(Pharm_Model_Answer(False, "C. Eliberarea mediatorului în fanta sinaptică — acțiunea sa asupra membranei postsinaptice — apariţia potențialului postsinaptic excitator — inactivarea enzimatica a mediatorului"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sinteza mediatorulu: — stocarea lui în vezicule — eliberarea în fanta sinaptică — acțiunea sa asupra membranei postsinaptice — apariția potențialului postsinaptic excitator — inactivarea enzimatica a mediatorului"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sinteza mediatorului —eliberarea în fanta sinaptică — acţiunea sa asupra membranei postsinaptice — apariția potenţialului postsinaptic excitator"))

_question       = Pharm_Model_Question("1.68 Care dintre următoarele afirmații referitoare la reflexul rotulian sunt adevărate?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Are arcul reflex constituit doar din doi neuroni"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este un reflex miotatic"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Este un reflex osteotendinos"))
_question.answers.append(Pharm_Model_Answer(False, "D. Aparține categoriei de reflexe polisinaptice"))
_question.answers.append(Pharm_Model_Answer(False, "E. Are în componenţa arcului său reflex cel puţin un neuron intercalar"))

_question       = Pharm_Model_Question("1.69 La nivelul maduvei spinarii se inchid urmatoarele reflexe:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. De tuse "))
_question.answers.append(Pharm_Model_Answer(False, "B. De vomă"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Ahilian"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Osteoiendinoase"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Nociceptive"))

_question       = Pharm_Model_Question("1.70 La nivelul trunchiului cerebral se închid următoarele reflexe:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. De mers"))
_question.answers.append(Pharm_Model_Answer(True,  "B. De deglutiție"))
_question.answers.append(Pharm_Model_Answer(True,  "C. De strănut"))
_question.answers.append(Pharm_Model_Answer(True,  "D. De supt"))
_question.answers.append(Pharm_Model_Answer(True,  "E. De masticație"))

_question       = Pharm_Model_Question("1.71 Cordoanele laterale ale măduvei conţin fasciculele:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Spinotalamice laterale"))
_question.answers.append(Pharm_Model_Answer(False, "B. Spinobulbare"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Spinocerebeloase directe (Flechsig)"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Spinocerebeloase încrucișate (Gowers)"))
_question.answers.append(Pharm_Model_Answer(False, "E. Piramidale directe"))


_question       = Pharm_Model_Question("1.72 Din cele 31 de perechi de nervi spinali:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. 8 aparţin regiunii cervicale"))
_question.answers.append(Pharm_Model_Answer(False, "B. 7 aparţin regiunii cervicale"))
_question.answers.append(Pharm_Model_Answer(False, "C. 4 se găsesc în regiunea coccigiană"))
_question.answers.append(Pharm_Model_Answer(True,  "D. 5 se păsesc în regiunea sacrală"))
_question.answers.append(Pharm_Model_Answer(True,  "E. 12 aparţin regiunii toracale"))

_question       = Pharm_Model_Question("1.73 Care dintre următoarele afirmaţii referitoare la rădăcinaanterioară a nervilor spinali sunt adevărate:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Este motorie "))
_question.answers.append(Pharm_Model_Answer(False, "B. Conţine axonii neuronilor senzoriali din ganglionii spinali"))
_question.answers.append(Pharm_Model_Answer(False, "C. Este senzitivă şi conţine dendritele neuronilor vegetativii"))
_question.answers.append(Pharm_Model_Answer(False, "D. Este constituită doar din axonii neuronilor visceromotori"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Conţine axonii neuronilor somatomotori din cornul anterior al măduvei ce conduc impulsuri spre musculatura scheletică"))

_question       = Pharm_Model_Question("1.74 Nervii cranieni prezintă o")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Rădăcină anterioară"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Origine reală"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Origine aparentă"))
_question.answers.append(Pharm_Model_Answer(False, "D. Rădăcină posterioară"))
_question.answers.append(Pharm_Model_Answer(False, "E. Ramură ventrală"))

_question       = Pharm_Model_Question("1.75 Fibrele vegetative motorii ale nervilor oculomotori inervează muşchii:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Muşchii intrinseci ai globului ocular"))
_question.answers.append(Pharm_Model_Answer(False, "B. Oblic superior al globului ocular"))
_question.answers.append(Pharm_Model_Answer(False, "C. Ridicător al pleoapei"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Muşchii circulari ai irisului"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Muşchii corpului cihar"))

_question       = Pharm_Model_Question("1.76. Fibrele motorii ale nervului facial inervează muşchii:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Limbii"))
_question.answers.append(Pharm_Model_Answer(False, "B. Masticatori"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Mimicii"))
_question.answers.append(Pharm_Model_Answer(False, "D. Faringelui"))
_question.answers.append(Pharm_Model_Answer(False, "E. Laringelui"))

_question       = Pharm_Model_Question("1.77 Fibrele motorii ale nervului glosofaringian inervează mușchii:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Limbii"))
_question.answers.append(Pharm_Model_Answer(False, "B. Sternocleidomastoidian"))
_question.answers.append(Pharm_Model_Answer(False, "C. Mimicii"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Faringelui"))
_question.answers.append(Pharm_Model_Answer(False, "E. Extrinseci ai globului ocular"))

_question       = Pharm_Model_Question("1.78 Centrii nervoși vegetativi coordonează și reglează funcţiileorganelor interne printr-o integrare:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Somatică"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Vegetativă propriu-zisă"))
_question.answers.append(Pharm_Model_Answer(False, "C. Somatomotorie"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Somato-vegetativă"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Neuro-endocrină"))

_question       = Pharm_Model_Question("1.79 Principalii centri nervoși vegetativi sunt localizați în:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Cerebel"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Măduva spinării"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Trunchiul cerebral"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Diencefal (hipotalamus)"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Sistemul limbic"))

_question       = Pharm_Model_Question("1.80 Stimularea simpatică produce următoarele efecte în organism:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Coronarodilataţie"))
_question.answers.append(Pharm_Model_Answer(False, "B. Bronhodilataţie"))
_question.answers.append(Pharm_Model_Answer(False, "C. Creşterea secreției lacrimale"))
_question.answers.append(Pharm_Model_Answer(False, "D. Inhibarea secreției gastrice şi intestinale"))
_question.answers.append(Pharm_Model_Answer(False, "E. Contracţia sfincterului vezical intern"))
