
from pharm_model.pharm_model  import *

"""*************************************************************************************************
****************************************************************************************************
*************************************************************************************************"""
_category         = Pharm_Model_Category()
_category.name    = "biologie analizatori"
PHARM_CATEGORY_2 = _category

"""*************************************************************************************************
****************************************************************************************************
*************************************************************************************************"""
_question       = Pharm_Model_Question("2.1 Selectaţi afirmaţiile corecte legate de segmentul periferic al analizatorilor:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Face legătura între segmentul de conducere"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Se mai numeşte şi receptor"))
_question.answers.append(Pharm_Model_Answer(False, "C. Poate fi format şi dintr-o celulă nespecializată, dar capabila de receptionarea unui anumit tip de energie din mediul intern consecutiva prezentei unui excitant nespecific"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Reuneşte un grup de celule specializate pentru receptionarea unui anumit tip de energie"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Are drept rol receptionareamodificarii unui anumit tip de energie care reprezinta excitantul specific"))

_question       = Pharm_Model_Question("2.2 Mecanoreceptorii sunt specializaţi în detectarea sensibilităților:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Tactila fina (de atingere)"))
_question.answers.append(Pharm_Model_Answer(False, "B. Termică"))
_question.answers.append(Pharm_Model_Answer(False, "C. Dureroasă"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Lactilă grosieră (de presiune)"))
_question.answers.append(Pharm_Model_Answer(False, "E. Olfactivă"))

_question       = Pharm_Model_Question("3.3. Precizați afirmaţiile corecte cu privire la caracteristicile receptorilor:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Specializarea lor contribuie la diferenţierea stimulilor"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Diferă structural de la un analizator la altul"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Pot fi incluși în organele de simţ"))
_question.answers.append(Pharm_Model_Answer(False, "D. Au o structură inexcitabilă"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Transformă acţiunea unui stimul în potenţial de receptor specific şi apoi in potential de actiune"))

_question       = Pharm_Model_Question("2.4 După teritoriul de recepționare a excitanţilor, receptoriianalizatorilor se clasifică în:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Baroreceptori"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Proprioceptori"))
_question.answers.append(Pharm_Model_Answer(False, "C. Fotoreceptori"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Exteroceptori"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Interoceptori"))

_question       = Pharm_Model_Question("2.5 După natura excitantului, receptorii se clasifică în:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Mecanoreceptori"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Chemoreceptori"))
_question.answers.append(Pharm_Model_Answer(False, "C. Proprioceptori"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Termoreceptori"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Electroreceptori"))

_question       = Pharm_Model_Question("2.6 Care dintre enunturile urmatoare legate de segmentul intermediar al analizatorilor sunt corecte?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Reuneste un grup de celule specializate in receptionarea unui anumit tip de energie"))
_question.answers.append(Pharm_Model_Answer(True, "B. Poate fi constituit din neuroni senzitivi ai nervilor cranieni"))
_question.answers.append(Pharm_Model_Answer(True, "C. Se mai numeste si calea aferenta"))
_question.answers.append(Pharm_Model_Answer(True, "D. Este constituit din neuroni pseudounipolari ai ganglionilor spinali"))
_question.answers.append(Pharm_Model_Answer(False, "E. Conduce eferent informatiile de la segmentul central spre structurile efectoare"))

_question       = Pharm_Model_Question("2.7 Analizatorul vizual are o in:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Aprecierea distanțelor"))
_question.answers.append(Pharm_Model_Answer(False, "B. Menţinerea echilibrului"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Diferenţierea luminozităţii"))
_question.answers.append(Pharm_Model_Answer(False, "D. Percepția sunetelor emise de fenomenele naturale"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Recunoaşterea formei obiectelor"))

_question       = Pharm_Model_Question("2.8 Selectaţi afirmaţiile corecte cu privire la cornee:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Este opacă"))
_question.answers.append(Pharm_Model_Answer(False, "B. Posedă în structura sa numeroase vase de sânge care-l asigură nutriția"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Nu este vascularizată"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Este transparentă"))
_question.answers.append(Pharm_Model_Answer(False, "E. Nu are în structura sa fibre nervoase"))

_question       = Pharm_Model_Question("2.9 Umoarea apoasă este:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. O lentilă biconcavă"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Secretată continuu de procesele ciliare și drenată prin sistemul venos al ochiului"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Un lichid transparent"))
_question.answers.append(Pharm_Model_Answer(False, "D. O substanţa opacă"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Unul din mediile transparente ale globului ocular"))

_question       = Pharm_Model_Question("2.10 Mediile transparente ale aparatului optic sunt reprezentate de:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Corpul vitros"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Cristalin"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Cornee"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Umoarea apoasă"))
_question.answers.append(Pharm_Model_Answer(False, "E. Coroidă"))

_question       = Pharm_Model_Question("2.11 Precizaţi afirmaţiile false cu privire la cristalin:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Are forma unei lentile biconvexe"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este opac"))
_question.answers.append(Pharm_Model_Answer(False, "C. Este localizat în spate irisului si legat de corpul ciliar prin ligamentul suspensor"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Conţine o bogată rețea de vase de sânge"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Are în structura sa numeroase fibre nervoase"))

_question       = Pharm_Model_Question("2.12 Care dintre următoarele afirmații cu privire la cristalin sunt corecte?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Are forma unei lentile biconcave"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este transparent"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Nu este vascularizat 3"))
_question.answers.append(Pharm_Model_Answer(True,  "D. La exterior este învelit de cristaloidă"))
_question.answers.append(Pharm_Model_Answer(False, "E. Este rezultatul secreției proceselor ciliare"))

_question       = Pharm_Model_Question("2.13 Corpul vitros al analizatorului vizual ocupă:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Camera anterioară a globului ocular împreună cu umoar"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Camera posterioară a globului ocular"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Spaţiul dintre cristalin şi retină Ă ului"))
_question.answers.append(Pharm_Model_Answer(False, "D. O poziţie centrală la nivelul giobului ocular, în spatele irisului"))
_question.answers.append(Pharm_Model_Answer(False, "E. Atât camera anterioară cât şi camera posterioară a globului ocular"))

_question       = Pharm_Model_Question("2.14 Care dintre următoarele structuri ale globului ocular sunt medii transparente?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Corpul vitros"))
_question.answers.append(Pharm_Model_Answer(False, "B. Pata galbenă"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Cornee"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Umoarea apoasă"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Cristalinul"))

_question       = Pharm_Model_Question("2.15. Tunica internă a globului ocular:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Este o structură cu 7 straturi celulare"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este reprezentată de retină"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Reprezintă segmentul receptor al analizatorului vizual!"))
_question.answers.append(Pharm_Model_Answer(False, "D. Prezintă numeroase terminaţii libere"))
_question.answers.append(Pharm_Model_Answer(False, "E. Are o structură fibroasă"))

_question       = Pharm_Model_Question("2.16 În structura retinei se întâlnesc:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Şase straturi celulare distincte"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Celule pigmentare cu rol în sinteza pigmenților fotosensibili"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Celule fotoreceptoare cu conuri ce au rol în vederea diurnă"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Celule fotoreceptoare cu bastonaş importante pentru vederea la lumină slabă, în cursul nopții"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Neuroni multipolari cu rol în procesul de convergenţă"))

_question       = Pharm_Model_Question("2.17 Selectaţi enunţul corect legat de repartiţia pe retină a celulelor fotoreceptoare:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. În pata galbenă se găsesc numai celule cu bastonaşe"))
_question.answers.append(Pharm_Model_Answer(False, "B. În fovea centralis predomină celule cu bastonaşe"))
_question.answers.append(Pharm_Model_Answer(False, "C. Celulele cu conuri sunt mai numeroase la periferia retinei"))
_question.answers.append(Pharm_Model_Answer(True,  "D. În fovea centralis se găsesc în exclusivitate celule cu conuri"))
_question.answers.append(Pharm_Model_Answer(False, "E. In pata galbenă se găsesc exclusiv celule cu conuri"))

_question       = Pharm_Model_Question("2.18. Ceelulele fotoreceptoare cu conuri joacă un rol important în vederea:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Nocturnă"))
_question.answers.append(Pharm_Model_Answer(False, "B. La lumină slabă"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Colorată"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Diurnă"))
_question.answers.append(Pharm_Model_Answer(False, "E. Stereoscopică"))

_question       = Pharm_Model_Question("2.19 Numărul celulelor cu conuri ale analizatorului vizual este de aproximativ:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. 3 miloane / retină"))
_question.answers.append(Pharm_Model_Answer(True,  "B. 7 milioane / retină"))
_question.answers.append(Pharm_Model_Answer(False, "C. 15 milioane / retină"))
_question.answers.append(Pharm_Model_Answer(False, "D. 10 milioane / retină"))
_question.answers.append(Pharm_Model_Answer(False, "E. 130 milioane / retină"))

_question       = Pharm_Model_Question("2.20. Numărul celulelor cu bastonaşe ale analizatorului vizual este de aproximativ:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. 3 milioane / retină"))
_question.answers.append(Pharm_Model_Answer(False, "B. 7 milioane / retină"))
_question.answers.append(Pharm_Model_Answer(False, "C. 25 milioane / retină"))
_question.answers.append(Pharm_Model_Answer(False, "D. 10 milioane / retină"))
_question.answers.append(Pharm_Model_Answer(True,  "E. 130 milioane / retină"))

_question       = Pharm_Model_Question("2.21 Care din următoarele afirmaţii legate de pigmenţii analizatoruluivizual sunt adevărate?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. lodopsina este pigmentul vizual conţinut numai de bastonaşe"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Bastonaşele conţin un singur pigment vizual numit rodopsină"))
_question.answers.append(Pharm_Model_Answer(False, "C. Cei doi pigmenţi fotosensibili, iodopsina şi rodopsina, sunt conținuți numai de celulele cu conuri"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Conurile conţin un singur pigment vizual numit iodopsină"))
_question.answers.append(Pharm_Model_Answer(False, "E. Bastonaşele conţin două tipuri de pigmenţi: iodopsina şi rodopsina"))

_question       = Pharm_Model_Question("2.22 Primul neuron al căii optice este reprezentat de:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Fovea centralis"))
_question.answers.append(Pharm_Model_Answer(False, "B. Cristalin"))
_question.answers.append(Pharm_Model_Answer(False, "C. Macula lutea"))
_question.answers.append(Pharm_Model_Answer(False, "D. Pata galbena"))
_question.answers.append(Pharm_Model_Answer(False, "E. Cornee"))

_question       = Pharm_Model_Question("2.23 Primul neuron al căii optice este reprezentat de celulele:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Piementare"))
_question.answers.append(Pharm_Model_Answer(False, "B. Multipolare"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Bipolare din retină"))
_question.answers.append(Pharm_Model_Answer(False, "D. Fotosensibile cu conuri"))
_question.answers.append(Pharm_Model_Answer(False, "E. Fotosensibile cu bastonaşe"))

_question       = Pharm_Model_Question("2.24. Al doilea neuron al căii optice este reprezentat de celulele:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Fotosensibile cu conuri"))
_question.answers.append(Pharm_Model_Answer(False, "B. Bipolare"))
_question.answers.append(Pharm_Model_Answer(False, "C. Pigmentare"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Multipolare retiniene"))
_question.answers.append(Pharm_Model_Answer(False, "E. Fotosensibile cu bastonaşe"))

_question       = Pharm_Model_Question("2.25. Al treilea neuron al căii optice se găseşte în:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Talamus"))
_question.answers.append(Pharm_Model_Answer(False, "B. Corpul geniculat medial"))
_question.answers.append(Pharm_Model_Answer(False, "C. Lobii occipitali ai emisferelor cerebrale"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Metatalamus"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Corpii geniculaţi laterali"))

_question       = Pharm_Model_Question("2.26 Aria vizuală (optică) primară este localizată:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. De-o parte şi de alta a scizurii calcarine"))
_question.answers.append(Pharm_Model_Answer(False, "B. Pe marginile şanţului central Rolando"))
_question.answers.append(Pharm_Model_Answer(False, "C. La nivelul coliculilor cvadrigemeni superiori"))
_question.answers.append(Pharm_Model_Answer(False, "D. Pe marginile scizurii laterale Sylvius"))
_question.answers.append(Pharm_Model_Answer(True,  "E. În lobii occipitali ai emisferelor cerebrale"))

_question       = Pharm_Model_Question("2.27 Organul lui Corti este aşezat pe membrana:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Ferestrei ovale"))
_question.answers.append(Pharm_Model_Answer(False, "B. Reissner"))
_question.answers.append(Pharm_Model_Answer(False, "C. Vestibulară"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Bazilară"))
_question.answers.append(Pharm_Model_Answer(False, "E. Timpanică"))

_question       = Pharm_Model_Question("2.28 Selectaţi afirmaţiile corecte legate de membrana tectoria:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True, "A. Este situată deasupra cililor celulelor senzoriale auditive"))
_question.answers.append(Pharm_Model_Answer(False, "B. Tapetează sistemul de oscioare"))
_question.answers.append(Pharm_Model_Answer(False, "C. Tapetează utricula şi sacula"))
_question.answers.append(Pharm_Model_Answer(False, "D. Se mai numeşte şi membrana Reissner"))
_question.answers.append(Pharm_Model_Answer(False, "E. Se situează dedesubtul cililor auditivi"))

_question       = Pharm_Model_Question("2.29. Deutoneuronul căii auditive se află în:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Ganglionul spiral Corti"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Nucleii cohleari din bulb"))
_question.answers.append(Pharm_Model_Answer(False, "C. Ganglionul spinal"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Nucleii cohleari din trunchiul cerebral"))
_question.answers.append(Pharm_Model_Answer(False, "E. Ganglionul vestibular Scarpa"))

_question       = Pharm_Model_Question("2.30 In cadrul mecanismului de producere al auzului, oscilaţiile perilimfei determină")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Oscilaţii ale membranei bazilare"))
_question.answers.append(Pharm_Model_Answer(False, "B. Amplificarea mișcărilor sistemului de oscioare din urechea medie"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Oscilaţii ale endolimfei"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Mărirea sau micşorarea distanței dintre celulele receptoare auditive şi membrana tectoria"))
_question.answers.append(Pharm_Model_Answer(False, "E. Vibraţiile membranei timpanale"))

_question       = Pharm_Model_Question("2.31 Al treilea neuron al analizatorului auditiv se găseşte în:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Metatalamus"))
_question.answers.append(Pharm_Model_Answer(False, "B. Corpul geniculat lateral"))
_question.answers.append(Pharm_Model_Answer(False, "C. Nucleul oculomotorului din trunchiul cerebral"))
_question.answers.append(Pharm_Model_Answer(False, "D. Girusul temporal superior"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Corpii geniculați mediali"))

_question       = Pharm_Model_Question("2.32 Peretele inferior al canalului cohlear este constituit din:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Membrana Reissner"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Lama spirală"))
_question.answers.append(Pharm_Model_Answer(False, "C. Hehcotremă"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Membrana bazilară"))
_question.answers.append(Pharm_Model_Answer(False, "E. Columelă"))

_question       = Pharm_Model_Question("2.33 În cadrul analizatorului auditiv, membrana bazilară vibrează:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. La baza melcului pentru sunetele de frecvenţe înalte"))
_question.answers.append(Pharm_Model_Answer(True,  "B. De la vârful melcului pentru sunetele cu frecvenţe joase"))
_question.answers.append(Pharm_Model_Answer(False, "C. Invers proporțional ca amplitudine cu intensitatea sunetului"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Consecutiv vibraţiilor perilimfei"))
_question.answers.append(Pharm_Model_Answer(False, "E. Odată cu deplasarea otolitelor în sens opus mişcării"))

_question       = Pharm_Model_Question("2.34 În mecanismul auzului, identificarea direcţiei din care vine sunetul se realizează prin:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Două mecanisme principale"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Analiza spațială vizuală"))
_question.answers.append(Pharm_Model_Answer(False, "C. Măsurarea amplitudini vibraţiei membranei bazilare"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Detectarea diferenţei de timp dintre semnalele acustice care ajung la cele două urechi"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Mişcări ale capului pe directia undei sonore"))

_question       = Pharm_Model_Question("2.35 In cadrul analizatorului vestibular, crestele ampulare sunt:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Constituite din celule receptoare ciliate"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Formate din celule de susținere"))
_question.answers.append(Pharm_Model_Answer(False, "C. Localizate pe membrana bazilară"))
_question.answers.append(Pharm_Model_Answer(False, "D. Înglobate într-o masă gelatinoasă dispusa pe membrana bazilara"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Localizate în ampulele canalelor semicirculare membroase"))

_question       = Pharm_Model_Question("2.36 În cadrul analizatorului vestibular, crestele ampulare şi cupolele gelatinoase se găsesc:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. La baza canalelor semicirculare"))
_question.answers.append(Pharm_Model_Answer(True,  "B. În nişte dilataţii ale canalelor semicirculare numite ampule"))
_question.answers.append(Pharm_Model_Answer(False, "C. În interiorul utriculei şi a saculei"))
_question.answers.append(Pharm_Model_Answer(False, "D. La nivelul organului Corti"))
_question.answers.append(Pharm_Model_Answer(False, "E. La baza melcului membranos"))

_question       = Pharm_Model_Question("2.37 Receptorii analizatorului vestibular sunt reprezentaţi de:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Otolite"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Crestele ampulare, pentru echilibrul dinamic"))
_question.answers.append(Pharm_Model_Answer(False, "C. Maculele utriculare şi saculare, pentru echilibrul dinamic"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Maculele utriculare și saculare, pentru echilibrul static"))
_question.answers.append(Pharm_Model_Answer(False, "E. Crestele ampulare, pentru echilibrul static"))

_question       = Pharm_Model_Question("11.38. Protoneuronul căii vestibulare se află în ganglionul:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Spinal Corti"))
_question.answers.append(Pharm_Model_Answer(False, "B. Spiral Corti"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Vestibular Scarpa"))
_question.answers.append(Pharm_Model_Answer(False, "D. Spinal Scarpa"))
_question.answers.append(Pharm_Model_Answer(False, "E. Cohlear"))

_question       = Pharm_Model_Question("2.39 De la deutoneuronii căii vestibulare pleacă fascicule spre:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Talamus, calea directă"))
_question.answers.append(Pharm_Model_Answer(False, "B. Epitalamus"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Nucleul roșu și formațiunea reticulată, căile colaterale"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Nucleii nervilor cranieni III, IV, VI, căile colaterale"))
_question.answers.append(Pharm_Model_Answer(False, "E. Corpul geniculat medial"))

_question       = Pharm_Model_Question("2.40 In reacțiile de redresare posturală se însumează informaţii rerecepționate de următorii analizatori:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Vestibular"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Kinestezic"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Vizual"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Cutanat"))
_question.answers.append(Pharm_Model_Answer(False, "E. Olfactiv"))

_question       = Pharm_Model_Question("2.41 Epidermul este alcătuit dintr-un țesut epitelial:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Unistratilicat keratinizat"))
_question.answers.append(Pharm_Model_Answer(False, "B. Pscudostratificat keratinizat"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Pluristratilicat keratinizat"))
_question.answers.append(Pharm_Model_Answer(False, "D. Cilindric stratificat keratinizat"))
_question.answers.append(Pharm_Model_Answer(False, "E. Cubic stratificat nekeratinizat"))

_question       = Pharm_Model_Question("2.42 Precizați afirmaţiile corecte cu privire la derm")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Este alcătuit din ţesut epitelial nekeratinizat"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este un ţesut conţunctiv dens"))
_question.answers.append(Pharm_Model_Answer(False, "C. Prezintă un epiteliu pavimentos stratificat"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Prezintă papile dermice"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Conţine corpusculii Krause"))

_question       = Pharm_Model_Question("2.43 In piele, corpusculii Krause sunt consideraţi:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Mecanoreceptori"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Termoreceptori"))
_question.answers.append(Pharm_Model_Answer(False, "C. Receptori pentru cald"))
_question.answers.append(Pharm_Model_Answer(False, "D. Algoreceptori"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Receptorii pentru rece"))

_question       = Pharm_Model_Question("2.44. Selectaţi răspunsurile corecte cu privire la hipoderm:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Conţine corpusculii Vater-Pacini"))
_question.answers.append(Pharm_Model_Answer(False, "B. Prezintă numeroase cute numite papilele dermice"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Reprezintă rezerva de grăsime subcutanată a organismului"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Este alcătuit din ţesut conjunctiv lax"))
_question.answers.append(Pharm_Model_Answer(False, "E. Beneficiază de o bogată rețea de terminaţii nervoase libere"))

_question       = Pharm_Model_Question("2.45 Selectaţi răspunsurile corecte cu privire la corpusculii Ruffini:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Sunt localizaţi în hipoderm"))
_question.answers.append(Pharm_Model_Answer(False, "B. Recepţionează presiunea şi deformarea tegumentară"))
_question.answers.append(Pharm_Model_Answer(False, "C. Sunt mai numeroși în tegumentele acoperite de păr"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Sunt consideraţi receptori pentru cald"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sunt receptori pentru rece"))

_question       = Pharm_Model_Question("2.46 Sensibilitatea dureroasă se manifestă mai intens la nivelul:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Vârfului limbii"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Buzelor"))
_question.answers.append(Pharm_Model_Answer(False, "C. Viscerelor"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Degetelor"))
_question.answers.append(Pharm_Model_Answer(False, "E. Organelor pline decât la cele cavitare"))

_question       = Pharm_Model_Question("2.47 Sensibilitatea termică este:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Recepţionată de terminații"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Neuniformă pe suprafața"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Consecința stimulării termorecetorilor de diferenta de temperatura dintre tegument si excitant"))
_question.answers.append(Pharm_Model_Answer(False, "D. Determinata de excitanti care produc deformari profunde ale tegumentului"))
_question.answers.append(Pharm_Model_Answer(False, "E. Uniform repartizată pe întreaga suprafață tegumentara"))

_question       = Pharm_Model_Question("2.48 Simţul gustului are rolul de a:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Determina temperatura alimentelor ingerate"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Aprecia calitatea alimentelor introduse în gură"))
_question.answers.append(Pharm_Model_Answer(False, "C. Aprecia calitatea aerului inhalat"))
_question.answers.append(Pharm_Model_Answer(False, "D. Informa asupra cantităţii alimentelor introduse în gură"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Intervenii în declanșarea secreţiilor digestive"))

_question       = Pharm_Model_Question("2.49 La nivel cerebral, aria gustativă este situată:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. In lobul parietal, în aceeaşi zonă unde se integrează şi sensibilitate tactila, termică şi dureroasă a limbii"))
_question.answers.append(Pharm_Model_Answer(False, "B. La nivelul talamusului"))
_question.answers.append(Pharm_Model_Answer(False, "C. Pe faţa medială a emisferelor cerebrale"))
_question.answers.append(Pharm_Model_Answer(True,  "D. La baza girusului parietal"))
_question.answers.append(Pharm_Model_Answer(False, "E. În jurul scizurii calcarine"))

_question       = Pharm_Model_Question("2.50 De la polul bazal al celulelor receptoare gustative pornesc fibrele:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Senzitive ale nervului VII ”"))
_question.answers.append(Pharm_Model_Answer(False, "B. Motorii ale nervului VI"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Senzitive ale nervului X"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Senzitive ale nervului IX"))
_question.answers.append(Pharm_Model_Answer(False, "E. Senzitive ale nervului V"))

_question       = Pharm_Model_Question("2.51 Care din următoarele afirmaţii referitoare la sunt adevărate?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Fohatele sunt în număr mare la vârful limbii"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Foliatele sunt prezente pe marginile posterioare ale limbii"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Circumvalatele formează la baza limbii „V”-ul lingual"))
_question.answers.append(Pharm_Model_Answer(False, "D. Filiformele formează la baza limbii „V”-ul lingual"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Fungiformele sunt răspândite pe marginile anterioare ale limbii"))

_question       = Pharm_Model_Question("2.52 Selectaţi afirmaţiile corecte referitoare la receptorii analizatorului olfactiv:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Fac sinapsa cu celulele mitrale in regiunea superioara a foselor nazale"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Sunt de tipul chemoreceptorilor"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Sunt neuroni bipolari senzitivi"))
_question.answers.append(Pharm_Model_Answer(False, "D. Strabat lama ciuruita a sfenoidului si patrund in cutia craniana"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Au o dendrita ce prezinta butoni olfactivi de unde pornesc 6-9 cili olfactivi receptori"))

_question       = Pharm_Model_Question("2.53 Selectaţi afirmaţiile corecte legate de axonii neuronilor bipolari din mucoasa olfactivă:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Formează tractul olfactiv"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Se inmănunchează pentru a forma nervii olfactivi"))
_question.answers.append(Pharm_Model_Answer(False, "C. Se proiectează in paleocortexul olfactiv"))
_question.answers.append(Pharm_Model_Answer(False, "D. Se termină cu o veziculă prevăzută cu 6-8 cili"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Străbat lama ciuruită a etmoidului"))


_question       = Pharm_Model_Question("2.54 Pentru a putea fi mirosită, o substanţă trebuie să îndeplineascăurmătoarele condiţii:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Să aibă o concentrație superioară pragului de excitabilitate celulară"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Să ajungă la receptorii olfactivi odată cu aerul inspirat"))
_question.answers.append(Pharm_Model_Answer(False, "C. Să aibă o concentraţie inferioară pragului de excitabilitate celulară"))
_question.answers.append(Pharm_Model_Answer(False, "D. Să fie insolubilă în pelicula de mucus, persistând mult timp pe aceasta"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Să fie volatilă"))

_question       = Pharm_Model_Question("2.55 Receptorii analizatorului kinestezic sunt prezenți în:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Capsule articulare"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Periost"))
_question.answers.append(Pharm_Model_Answer(False, "C. Epiderm"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Tendoane"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Muşchi"))

_question       = Pharm_Model_Question("2.56 Fibrele musculare intrafusale prezintă:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Extremităţile prinse pe tendoane"))
_question.answers.append(Pharm_Model_Answer(True,  "B. O porţiune centrală necontractilă"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Extremităţi striate contractile"))
_question.answers.append(Pharm_Model_Answer(False, "D. Numeroase miofibrile"))
_question.answers.append(Pharm_Model_Answer(False, "E. Puţini nuclei în zona centrală necontractilă"))

_question       = Pharm_Model_Question("2.57 Organele tendinoase Golgi sunt:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Situate printre fibrele musculare netede"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Stimulate de creşterea tensiunii în muşchi determinată de contracția musculară"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Localizate în tendoane"))
_question.answers.append(Pharm_Model_Answer(False, "D. Înrudite cu corpusculii Vater-Pacini din piele"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Prezente în ligamente"))

_question       = Pharm_Model_Question("2.58 Selectati raspunsurile corecte cu privire la cataracta:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reprezinta opacifierea cristalinului"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Se manifesta prin vedere dubla sau multipla"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Apare mai frecvent la pacientii cu diabet zaharat, artrita, arterioscleroza"))
_question.answers.append(Pharm_Model_Answer(False, "D. Este consecinta cresterii tensiunii intraoculare"))
_question.answers.append(Pharm_Model_Answer(False, "E. Are la baza ei o infectie microbiana sau virala recidivanta"))

_question       = Pharm_Model_Question("2.59 Precizati afirmatiile corecte cu privire la glaucom")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Se datoreaza opacifierii cristalinului"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este consecinta cresterii tensiunii intraoculare"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Se traduce clinic prin tulburari de vedere consecutiv reducerii campului vizual"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Reprezinta o cauza de pierdere a vederii"))
_question.answers.append(Pharm_Model_Answer(False, "E. Este o afectiune a conjuctivei ochiului, de etiologie alergica"))

_question       = Pharm_Model_Question("2.60 Selectaţi răspunsurile corecte cu privire la rinite:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Se caracterizează printr-o secreție nazală apoasă şi abundentă"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Sunt consecința unui proces inflamator de etiologie virală, de cele mai multe ori, şi localizat la nivelul mucoasei nazale"))
_question.answers.append(Pharm_Model_Answer(False, "C. Sunt afecţiuni cu o etiologie multifactorială"))
_question.answers.append(Pharm_Model_Answer(False, "D. Afectează în special persoanele în vârstă"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sunt determinate de dezvoltarea unor ciuperci din genul Candida pe mucoasa nazală"))

_question       = Pharm_Model_Question("2.61 Precizați afirmaţiile corecte cu privire la caracteristicile procesului de adaptare a ochiului la întuneric")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Scade pragul de excitabilitate al celulelor fotoreceptoare"))
_question.answers.append(Pharm_Model_Answer(False, "B. Scade cantitatea de iodopsină"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Creşte cantitatea pigmenţilor fotosensibili"))
_question.answers.append(Pharm_Model_Answer(False, "D. Necesită un interval de timp de 5 minute"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Durează 30-40 minute"))

_question       = Pharm_Model_Question("2.62 Procesul de adaptare a ochiului pentru vederea la distanță necesită următoarele modificări:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False,  "A. Bombarea cristalinului"))
_question.answers.append(Pharm_Model_Answer(True,   "B. Relaxarea mușchiului ciliar circular"))
_question.answers.append(Pharm_Model_Answer(True,   "C. Punerea în tensiune a ligamentului suspensor al cristalinului prin intervenţia mușchilor radiari"))
_question.answers.append(Pharm_Model_Answer(False,  "D. Contracția mușchilor radiari determinată de parasimpatic"))
_question.answers.append(Pharm_Model_Answer(True,   "E. Aplauzarea cristalinului"))

_question       = Pharm_Model_Question("2.63 Care sunt modificarile la nivelul ochiului ce favorizeaza vederea de aproape a obiectelor?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Relaxarea ligamentului suspensor al cristalinului"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Contractia muschilor circulari"))
_question.answers.append(Pharm_Model_Answer(False, "C. Muschiul ciliar se relaxeaza"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Bombarea cristalinului"))
_question.answers.append(Pharm_Model_Answer(False, "E. Contractia fibrelor simpatice ale oculomotorului asupra muschilor radiari"))

_question       = Pharm_Model_Question("2.64 Care sunt fnctorii de care depinde sensibilitatea retinei la stimulul luminos?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Elasticitatea cristalinului"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Natura luminii"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Durata iluminarii"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Dimensiunea sursei de lumina"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Zona retiniana iluminata"))

_question       = Pharm_Model_Question("2.65 Percepția culorii albe a obiectelor este:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Obţinută prin descompunerea inegală a celor patru culori fundamentale: roşu. palben, verde şi albastru"))
_question.answers.append(Pharm_Model_Answer(False, "B. Consecutivă scăderii cantității de iodopsină din celulele cu conuri"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Consecința descompunerii uniforme a celor trei culori fundamentale: roşu, verde şi albastru"))
_question.answers.append(Pharm_Model_Answer(False, "D. Procesul rezultat al scăderii cantității de iodopsina din celulele cu bastonaşe"))
_question.answers.append(Pharm_Model_Answer(False, "E. Rezultatul descompunerii uniforme a celor trei substante fotosensibile: rosu, galben si albastru"))

_question       = Pharm_Model_Question("2.66 Selectaţi răspunsurile corecte cu privire la rampa timpanică:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Conţine celulele senzoriale ciliate auditive"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Comunică cu fereastra rotundă"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Aparține segmentului receptor al analizatorului auditiv"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Comunică cu rampă vestibulară la nivelul helicotremei"))
_question.answers.append(Pharm_Model_Answer(False, "E. Este situată la vârful melcului"))

_question       = Pharm_Model_Question("2.67 La frecvente inalte ale undelor sonore se produce vibratia:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Membranei bazilare de la baza melcului"))
_question.answers.append(Pharm_Model_Answer(False, "B. Membranei Reissner"))
_question.answers.append(Pharm_Model_Answer(False, "C. Lamei spirale"))
_question.answers.append(Pharm_Model_Answer(False, "D. Membranei bazilare de la varful melcului"))
_question.answers.append(Pharm_Model_Answer(False, "E. Organul Corti"))

_question       = Pharm_Model_Question("2.68 Care din următoarele afirmații referitoare la maculele din utricula si sacula sunt adevarate?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Conţin epitelii senzoriale diferite"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Constituie aparatul otolitic bula"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Sunt receptorii analizatorului vestibular"))
_question.answers.append(Pharm_Model_Answer(False, "D. Reprezintă segmentul receptor al analizatorului acustic"))
_question.answers.append(Pharm_Model_Answer(False, "E. Sunt receptori ai echilibrului dinamic"))

_question       = Pharm_Model_Question("2.69 Selectaţi afirmaţiile adevărate cu privire la protoneuronul câii vestibulare")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Axonul lui intră în compoziţia fasciculului vestibulo-spinal"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Se găsește în ganglionul Scarpa"))
_question.answers.append(Pharm_Model_Answer(False, "C. Nu are o localizare bine precizată"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Axonul lui participă la formarea ramurii vestibulare a nervului VIII"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Prin dendrite este conectat cu celulele receptoare vestibulare"))

_question       = Pharm_Model_Question("2.70 Precizaţi afirmaţiile false cu privire la sensibilitatea dureroasă:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Este responsabilă de reacţia organismului la deformările ușoare alctegumentului"))
_question.answers.append(Pharm_Model_Answer(False, "B. Este capacitatea de percepere şi reacționare a organismului la diferițistimuli nespecifici, care provoacă leziuni celulare"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Are drept receptori proprii terminaţiile nervoase libere și corpusculii Krause"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Are capacitatea de a detecta diferenţele de temperatură din exteriorul corpului uman"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Se caracterizează printr-o densitate mare de receptori cu localizare la nivelul papilelor dermice"))

_question       = Pharm_Model_Question("2.71 Selectaţi afirmaţiile corecte referitoare la nucleul solitar:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Reprezintă nucleul spre care converg fibrele senzitive ale nervilor cranieni VII, IX şi X"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este localizat în bulb"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Conţine deutoneuronii căii gustative"))
_question.answers.append(Pharm_Model_Answer(False, "D. Aparține metatalamusului"))
_question.answers.append(Pharm_Model_Answer(False, "E. Este o componenta a segmentului receptor al analizatorului gustativ "))

_question       = Pharm_Model_Question("2.72 Precizați afirmaţiile corecte cu privire la celulelemucoasa olfactivă:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Sunt de tipul baroreceptorilor"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Sunt dispuse în regiunea superioară a foselor nazale"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Au rol de protoneuron al căii olfactive"))
_question.answers.append(Pharm_Model_Answer(False, "D. Se mai numesc celule mitrale si reprezintă deutoneuronul căii olfactive"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Au in portiunea terminala a dendritelor butoni olfactivi de la care pleaca 6-8 cili olfactivi receptori"))


_question       = Pharm_Model_Question("2.73 Selectaţi răspunsurile corecte cu privire la conjunetivită:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(True,  "A. Poate fi consecutiva unei etiologii infectioase sau virala"))
_question.answers.append(Pharm_Model_Answer(False, "B. Este consecinta opacifierii cristalinului"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Apare consecutiv unui proces imflamator la nivelul conjuctivei globului ocular"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Se caracterizeaza prin senzatia de corp strain in ochi"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Se manifesta clinic prin secretie lacrimala abudenta"))

_question       = Pharm_Model_Question("2.74 Care dintre afirmatiile urmatoare nu sunt caracteristice acneei?")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Afecteaza in special persoanele tinere, adolescentii"))
_question.answers.append(Pharm_Model_Answer(False, "B. Este consecinta unor tulburari functionale la nivelul glandelo sebacee datorate de cele mai multe ori unui dezechilibru hormonal care apare la pubertate"))
_question.answers.append(Pharm_Model_Answer(True,  "C. Se manifesta clinic prin aparitia la nivelul fetei a unor vezicule mici, grupate in buchet"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Este o afectiune de etiologie streptococica sau stafilococica, supurativa cu localizare la nivelul pielii"))
_question.answers.append(Pharm_Model_Answer(False, "E. Se manifesta prin seboree, localizata in special la pielea fetei"))

_question       = Pharm_Model_Question("2.75 Precizaţi afirmaţiile corecte cu referitoare la otită medie:")
_category.questions.append(_question)
_question.answers.append(Pharm_Model_Answer(False, "A. Se produce consecutiv parazitării pielii de către unele specii de ciuperci"))
_question.answers.append(Pharm_Model_Answer(True,  "B. Este cea mai frecventă formă de otită"))
_question.answers.append(Pharm_Model_Answer(False, "C. Se caracterizează printr-o inflamație la nivelul urechii medii de etiologie alergică"))
_question.answers.append(Pharm_Model_Answer(True,  "D. Are la baza sa o etiologie microbiană sau virală"))
_question.answers.append(Pharm_Model_Answer(True,  "E. Poate să se traducă clinic prin durere auriculară locală, febră, frison si diminuarea perceptiei auditive"))
